name: traefik


networks:
  default:
    name: traefik
  web:
    name: web
    internal: true


services:
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: always
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: "0.1"
          memory: 64M
        limits:
          cpus: "0.5"
          memory: 256M
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      default: {}
      web: {}
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "8080:8080/tcp"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      start_period: 15s
      timeout: 2s
      retries: 3
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # - "--accesslog=true"
      # Entrypoints
      - "--entryPoints.http.address=:80"
      - "--entryPoints.http.forwardedHeaders.trustedIPs=${CLOUDFLARE_IPS}"
      - "--entryPoints.https.address=:443"
      - "--entrypoints.https.http.tls.certResolver=le"
      - "--entryPoints.https.http3=true"
      - "--entryPoints.https.forwardedHeaders.trustedIPs=${CLOUDFLARE_IPS}"
      - "--entryPoints.traefik.address=:8080"
      - "--entrypoints.metrics.address=:9200"
      # API & Ping
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--ping=true"
      # SSL
      - "--certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/certs/acme.json"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      # Metrics
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addrouterslabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.entrypoint=metrics"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "7"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${DATA_DIR}/traefik/certs:/certs"
    environment:
      TZ: "${TZ:-UTC}"
      CF_DNS_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
      TRAEFIK_LOG_FORMAT: "json"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.http.middlewares.cloudflare-only.ipallowlist.sourcerange: "${CLOUDFLARE_IPS}"

